project_id = "tyrsrwmwwfqdzsmogjwb"

[functions.delete-account]
verify_jwt = true

[functions.nmkr-proxy]
verify_jwt = false

[functions.project-cleanup]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.blockfrost-webhook]
verify_jwt = false

[functions.create-marketing-payment-intent]
verify_jwt = false

[functions.marketing-scheduler]
verify_jwt = false

[functions.content-moderation]
verify_jwt = false

[functions.og-handler]
verify_jwt = false

[functions.health-check]
verify_jwt = false

[functions.get-wallet-balance]
verify_jwt = false

[functions.wallet-auth]
verify_jwt = false
