project_id = "tyrsrwmwwfqdzsmogjwb"

[functions.delete-account]
verify_jwt = true

[functions.nmkr-proxy]
verify_jwt = false

[functions.project-cleanup]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = true

[functions.blockfrost-webhook]
verify_jwt = false
